### ISSUE TITLE
Can't get Offset to work

### ISSUE THREAD

**Issue by James-F2** [NRGDEAD/Cue2cu2#1]
Here is my command:
> python cue2cu2.py TEMP.cue -o=-00:00:02

Here is the output:
![cmd](https://user-images.githubusercontent.com/31185814/76294653-ecd4d900-62bb-11ea-8f52-c9dc52d3869c.png)

**Comment by NRGDEAD** [comment]
Ah, I figured GitHub would send me an e-mail or something. Didn't see you opened an issue for 7 days. D-:
Thanks for waiting. I apparently forgot to test --offset with the new format and missed a variable name there. It's already fixed in the commit I just pushed.

Side note: I think you want to change only the audio tracks because of the recent discussion in the PSIO forum about the audio being cut off in the beginning, right? At the moment, the data track will also be shifted. But since that is a bit rigid, I'm thinking about splitting --offset up to individual offsets for audio, data, size and trk end. Will probably have a look at that in the upcoming days. If you have any suggestions, let me know. I'll leave this issue open until I implemented something.

**Comment by NRGDEAD** [comment]
I added --offset-select, which enables you to apply the offset to only the variables you wish. Also the default is changed to audio tracks, pregaps, and track end. See the README.md for the details. Hope that helps. I'm closing this issue report; please feel free to a new one if you encounter another bug! Thanks again.
